### ISSUE TITLE
Vim Compose: Native host is not installed

### ISSUE THREAD

**Issue by praharshbhatt** [mbid/vim-compose#2]
Vim Compose: Native host is not installed

![image](https://github.com/user-attachments/assets/786f1a6b-0465-47c8-9dff-c7888cda03a7)

Retro steps:
1. Install extension.
2. Install vim-compose
```
git clone https://github.com/mbid/vim-compose
cd vim-compose
./install-native-host
```
3. Reboot
4. open `Brave Browser`, press `ctrl+shift+e`

**Comment by mbid** [comment]
Hi Praharsh, sorry to hear about this problem. Have you made sure that you've installed not just the browser extension but also the native executable? This should work:
```
git clone https://github.com/mbid/vim-compose
cd vim-compose
./install-native-host
```

If you've installed the app: What's your operating system? And unfortunately I haven't tried this extension with brave. @EthanJamesLew has added support for brave, maybe he knows what might be the problem here.

**Comment by praharshbhatt** [comment]
I am using mint.

I had brave installed in flatpak.
After reinstalling from binary, the issue is fixed! :)

**Comment by mbid** [comment]
Ah, yes, I think flatpak apps get their own home directory. That's probably why the brave instance you installed via flatpak did not pick up on the native host executable. Good to hear that you managed to resolve the issue, and thanks for letting us now!
